---
title: "Worksheet 3b"
author: "Kylene Joy Yanguas"
date: "2022-11-13"
output: pdf_document
---

```{r, include= TRUE}
#1. Create a data frame using the table below.
# a.Write the codes.

Respondents <- c(1:20)
Sex <-c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2)
Fathers_Occupation <-c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1)
Persons_at_home <-c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6)
Siblings_at_school <-c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2)
Types_of_houses <-c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2)

data_frame <- data.frame(Respondents, Sex, Fathers_Occupation,Persons_at_home,
                     Siblings_at_school,Types_of_houses)             
data_frame
```
```{r, include= TRUE}
#b.Describe the data. Get the structure or the summary of the data

summary(data_frame)

```
```{r, include= TRUE}
#c. Is the mean number of siblings attending is 5?

# No, the mean is 2.95 
```
```{r, include= TRUE}
#d. Extract the 1st two rows and then all the columns using the subsetting functions.
#Write the codes and its output.

sub1 <- subset(data_frame[1:2, 1:6, drop = FALSE])
sub1
```
```{r setup, include= TRUE}
#e. Extract 3rd and 5th row with 2nd and 4th column. Write the codes and its
#result.
sub2 <- subset(data_frame[c(3,5),c(2,4)])
sub2
```
```{r, include= TRUE}
#f. Select the variable types of houses then store the vector that results as types_houses.
#Write the codes.
sub3 <- subset(data_frame[c(1:20), c(2,6)])

type_houses <- sub3

```
```{r, include= TRUE}
#g. Select only all Males respondent that their father occupation was farmer. Write
#the codes and its output.

sub4 <- subset(data_frame[c(3,11),c(2,3)])
sub4

```
```{r, include=TRUE}
#h. Select only all females respondent that have greater than or equal to 5 number of siblings attending school. Write the codes and its outputs

sub5 <- subset(data_frame[c(1:20), c(2,5)])
female_resp <- sub5[data_frame$Siblingsatschool >= 5,]
female_resp
```
```{r, include= TRUE}
#2. Write a R program to create an empty data frame. Using the following codes:
df = data.frame(Ints=integer(),
                Doubles=double(), Characters=character(),
                Logicals=logical(),
                Factors=factor(),
                stringsAsFactors=FALSE)
print("Structure of the empty dataframe:")
print(str(df))
```
```{r, include= TRUE}
#a. Describe the results.
#There is zero observations but has a 5 variables. It shows 
#that ther is no data available in table.

#3. Interpret the graph.
#The data show that the counts of negative sentiments is the highest from July
#14 to 21,2020. 

```

